# Generated by Django 5.1.1 on 2025-08-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventHall',
            fields=[
                ('hall_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('hall_name', models.CharField(max_length=100)),
                ('is_hall_ac', models.BooleanField(default=False)),
                ('is_dining_ac', models.BooleanField(default=False)),
                ('max_hall_capacity', models.IntegerField(default=1000)),
                ('max_dining_capacity', models.IntegerField(default=1000)),
                ('is_parking', models.BooleanField(default=False)),
                ('max_parking_capacity', models.IntegerField(default=500)),
                ('is_bride_groom_room', models.BooleanField(default=False)),
                ('is_bride_groom_room_ac', models.BooleanField(default=False)),
                ('is_relative_rooms', models.BooleanField(default=False)),
                ('relative_rooms_count', models.IntegerField(default=5)),
                ('is_relative_rooms_ac', models.BooleanField(default=False)),
                ('is_kitchen_facility', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('hall_image', models.ImageField(null=True, upload_to='')),
                ('nationality', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=50)),
                ('door_no', models.CharField(max_length=20)),
                ('owner_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
    ]
