# Generated by Django 5.1.1 on 2025-08-05 10:05

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('language', models.CharField(choices=[('Tamil', 'Tamil'), ('English', 'English'), ('Malayalam', 'Malayalam'), ('Kanada', 'Kanada'), ('Telugu', 'Telugu'), ('Hindi', 'Hindi')], max_length=50)),
                ('type', models.CharField(choices=[('Music', 'Music'), ('Comedy', 'Comedy'), ('Speech', 'Speech'), ('Dance', 'Dance'), ('Movie', 'Movie')], max_length=50)),
                ('age_limit', models.IntegerField(default=18)),
                ('keywords', django_mysql.models.ListTextField(models.IntegerField(), size=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('organizer', models.CharField(max_length=100)),
            ],
        ),
    ]
