# Generated by Django 5.1.1 on 2025-08-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_seat_count',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
