# Generated by Django 5.1.1 on 2025-08-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventhall',
            name='pincode',
            field=models.IntegerField(default=600001),
        ),
    ]
