# Generated by Django 5.1.1 on 2025-08-06 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='available_seat_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='total_seat_count',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('booking_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=18)),
                ('seat_number', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_booking', to='api.event')),
            ],
        ),
    ]
