# Generated by Django 5.1.1 on 2025-08-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_total_seat_count_alter_event_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='available_seat_count',
            field=models.IntegerField(null=True),
        ),
    ]
