# Generated by Django 5.1.1 on 2025-08-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_eventhall_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventhall',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
