# Generated by Django 5.1.1 on 2025-08-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_available_seat_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_seat_count',
            field=models.IntegerField(null=True),
        ),
    ]
