# Generated by Django 5.1.1 on 2025-08-05 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_event_available_seat_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('seat_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_booking', to='api.event')),
            ],
        ),
    ]
